language: android
jdk: oraclejdk7
android:
    components:
        - build-tools-22.0.1
        - android-22
        - platform-tools
        - extra-android-support
        - extra-google-google_play_services
        - extra-android-m2repository
    licenses:
        - 'android-sdk-license-.+'